### ISSUE TITLE
scrypt

### ISSUE THREAD

**Issue by awesterb** [bwesterb/pol#13]
After running `pol init`, and providing a master-password, I get the following error. 

> OSError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_scrypt.so, 6): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
>      Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_scrypt.so
>      Reason: image not found

While the problem, that the file `libcrypto.1.0.0.dylib` is not in the directory `/usr/local/opt/openssl/lib/` but in `/opt/local/lib/`, is not due to pol, its solution might fit in the README.rst file.

**Comment by bwesterb** [comment]
Seems to be an scrypt bug.  I put a workaround ( f9a2a3ba1739886919c51f291ca6215bb27075ac  ) in the README.
