### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [bwesterb/pol#19]
### Description:

In the "pol/src/importers/keepass.py", I have identified a security vulnerability about insecure cryptographic algorithm. ECB mode encryption is not semantically secure, which means it might cause information leakage.

### Location:

https://github.com/bwesterb/pol/blob/master/src/importers/keepass.py#L44

```python
cipher = Crypto.Cipher.AES.new(master_seed2, Crypto.Cipher.AES.MODE_ECB)
```

### Reference

- **CWE-327: Use of a Broken or Risky Cryptographic Algorithm**

### Recommendate

Use other cipher mode such as CFB or CTR with random IV.

**Comment by bwesterb** [comment]
Not used in a vulnerable way.
